version: "3.8"

networks:
  default:
    name: typingrealm
    external: true

services:
  nitrotype-team-api:
    image: ghcr.io/ewancoder/nitrotype-team-api:main
    container_name: nitrotype-team-api
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
